### ISSUE TITLE
Code Checkout Bug

### ISSUE THREAD

**Issue by mikecarr2** [bridgecrewio/yor-action#160]
When a branch is the same name as a file within the repo, the Yor action fails with: 

> /usr/bin/git checkout branch
> fatal: 'branch' could be both a local file and a tracking branch.
> Please use -- (and optionally --no-guess) to disambiguate

This [issue](https://github.com/JamesIves/github-pages-deploy-action/issues/45) in a different project suggests changing the below line from `checkout` to `switch` should fix this. 
https://github.com/bridgecrewio/yor-action/blob/2320f4cc960e0b9f5407a4044f5cd63bd4260c59/src/main.ts#L18

**Comment by gruebel** [comment]
hey @mikecarr2 thanks for reaching out.
Sounds like a good idea, since you already know what to change, how about doing a contribution? 🙂

**Comment by BigDog2071** [comment]
> When a branch is the same name as a file within the repo, the Yor action fails with:
> 
> > /usr/bin/git checkout branch
> > fatal: 'branch' could be both a local file and a tracking branch.
> > Please use -- (and optionally --no-guess) to disambiguate
> 
> This [issue](https://github.com/JamesIves/github-pages-deploy-action/issues/45) in a different project suggests changing the below line from `checkout` to `switch` should fix this.
> 
> https://github.com/bridgecrewio/yor-action/blob/2320f4cc960e0b9f5407a4044f5cd63bd4260c59/src/main.ts#L18
