### ISSUE TITLE
Tags inserted into aws_iam_policy resource seems to cause an issue

### ISSUE THREAD

**Issue by stevendotdelahunty** [bridgecrewio/yor-action#4]
### Description
We have a tf file with an `aws_iam_policy` resource declared like so:

`iam.tf`
```hcl
resource "aws_iam_policy" "additional_policy" {

  name        = "my-policy"
  policy      = var.additional_role_policy
  path        = var.iam_path
  description = var.description
  tags = {
    git_commit           = "redacted"
    git_file             = "redacted.tf"
    git_last_modified_at = "redacted"
    git_last_modified_by = "redacted"
    git_modifiers        = "redacted"
    git_org              = "redacted"
    git_repo             = "redacted"
    yor_trace            = "redacted"
  }
}
```
The tags attribute is inserted by the yor-action. 

Unfortunately, we run into the following exception:
```
Error: Unsupported argument

  on .terraform/modules/mymodule/iam.tf line 94, in resource "aws_iam_policy" "additional_policy":
  94:   tags = {

An argument named "tags" is not expected here.

```

When we remove the tags and re-run, the `terraform plan` succeeds. However, when we push to source control, this action is re-adding the tags.

We can obviously work around this by disabling the `yor-action` but we think it might need some investigation and a fix putting out.

**Comment by nimrodkor** [comment]
Thanks for reporting @stevendotdelahunty !

I wonder what the source of the issue is, since according to the docs - `aws_iam_policy` supports tags
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy

**Comment by nimrodkor** [comment]
What's your terraform and aws provider versions?

**Comment by nimrodkor** [comment]
I've tried to apply this:
```terraform
resource "aws_iam_policy" "my_policy" {
  policy = data.aws_iam_policy_document.my_doc.json
  name   = "Nimrod-policy"
  tags = {
    git_commit           = "redacted"
    git_file             = "redacted.tf"
    git_last_modified_at = "2021-11-09 15:21:21"
    git_last_modified_by = "redacted"
    git_modifiers        = "redacted"
    git_org              = "redacted"
    git_repo             = "redacted"
    yor_trace            = "redacted"
  }
}
```

And it worked. However - I do see the file path is inside `.terraform` directory - which means it is an internal module file. It's not recommended to tag the `.terraform` dir - yor has it in its `ignored_dirs`:
https://github.com/bridgecrewio/yor/blob/3a89e3de92368fdab151252bef670c6597c42a85/src/terraform/structure/terraform_parser.go#L29

Can you maybe share the pipeline that led to these tags being created?

**Comment by stevendotdelahunty** [comment]
Hi @nimrodkor, thanks for replying so promptly!

I agree, the provider docs do suggest there should be no issue with the tags attribute in that resource.

Provider version for the implementation is `version = "~> 2.6"`.

The GitHub Action step is doing nothing much:
```yaml
      - name: Run yor action and commit
        uses: bridgecrewio/yor-action@main
```

**Comment by stevendotdelahunty** [comment]
> It's not recommended to tag the .terraform dir - yor has it in its ignored_dirs:
In regards to this, so the module is managed in a separate repo and that's where the yor-action adds the tags.
The implementation of the module is in another repo which is pulling in the module to the `.terraform` directory and attempting to use the module.

I'm trying to get a small sandbox with this module running with a newer AWS provider version to try and eliminate that. If that's the issue then it shouldn't be too painful to resolve.

**Comment by nimrodkor** [comment]
I think it might be an issue with the fact you're using a pretty old tf aws provider version... Can you try to update it? @stevendotdelahunty
